name: Continuous Integration

on: [pull_request, push]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Compile and test
        run: |
          mkdir -p bin
          javac -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" -d bin src/edu/ucalgary/oop/*.java test/edu/ucalgary/oop/*.java
          java -cp "bin:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore edu.ucalgary.oop.AnimalTest edu.ucalgary.oop.CleaningCageTest edu.ucalgary.oop.FeedingScheduleTest edu.ucalgary.oop.TaskTest edu.ucalgary.oop.TreatmentTest
